Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.fft import rfft, rfftfreq
from scipy.io.wavfile import read #import the required function from the module
import matplotlib.pyplot as plt
import numpy as np
samplerate, y = read('CantinaBand3.wav')
duration = len(y)/samplerate
time = np.arange(0,duration,1/samplerate) #time vector

# MatplotLib Settings:
plt.style.use('default') # Matplotlib Style w√§hlen
plt.figure(figsize=(8,3)) # Plot-Gr√∂√üe
plt.rcParams['font.size'] = 10; # Schriftgr√∂√üe

y_normalized = np.int16((y / y.max()) * 32767)
# Note the extra 'r' at the front
yf = rfft(y_normalized)/5e6
xf = rfftfreq(len(y), 1 / Fs)

plt.subplot(1,2,1)
plt.plot(time,y, 'tab:blue')
plt.xlabel('Zeit (s)')
plt.ylabel('Amplitude')
plt.title('Audio-Signal im Zeitbereich')

plt.subplot(1,2,2)
plt.plot(xf,np.abs(yf),'tab:red') # plotting the spectrum
plt.xlabel('Frequenz (Hz)')
plt.ylabel('Power')
plt.title('Audio-Signal im Frequenzbereich')
plt.tight_layout()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [7][0m, in [0;36m<cell line: 17>[0;34m()[0m
[1;32m     15[0m [38;5;66;03m# Note the extra 'r' at the front[39;00m
[1;32m     16[0m yf [38;5;241m=[39m rfft(y_normalized)[38;5;241m/[39m[38;5;241m5e6[39m
[0;32m---> 17[0m xf [38;5;241m=[39m rfftfreq([38;5;28mlen[39m(y), [38;5;241m1[39m [38;5;241m/[39m [43mFs[49m)
[1;32m     19[0m plt[38;5;241m.[39msubplot([38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m1[39m)
[1;32m     20[0m plt[38;5;241m.[39mplot(time,y, [38;5;124m'[39m[38;5;124mtab:blue[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'Fs' is not defined
NameError: name 'Fs' is not defined

