Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# MatplotLib Settings:
plt.style.use('default') # Matplotlib Style w√§hlen
plt.figure(figsize=(8,3)) # Plot-Gr√∂√üe
#plt.xkcd()
plt.rcParams['font.size'] = 10; # Schriftgr√∂√üe
A = 1.0
M_p = 4.0
PM = A * np.sin(2*np.pi*ff*t + M_p*y_nutz_norm)
plt.subplot(1,2,1)
plt.plot(t, y, 'k', ls=':', label = 'Tr√§ger')
plt.plot(t,PM, 'tab:red', lw=2, alpha = 0.65, label = 'AM')
plt.plot(t, y_nutz_norm, 'tab:blue', label = 'Nachricht')
plt.title('Phasenmodulation (PM)')
plt.xlim([0.0,0.013])
#plt.ylim([-1.5,1.5])
plt.xlabel('Zeit (s)')
plt.ylabel('Amplitude')

# FM
M_f = 1.0
FM = A * np.sin(2*np.pi*ff*t + M_f*(np.cumsum(y_nutz_norm)))
plt.subplot(1,2,2)
plt.plot(t, y, 'k', ls=':', label = 'Tr√§ger')
plt.plot(t,FM, 'tab:red', lw=2, alpha = 0.65, label = 'FM')
plt.plot(t, y_nutz_norm, 'tab:blue', label = 'Nachricht')
plt.title('Frequenzmodulation (FM)')
plt.xlim([0.0,0.013])
#plt.ylim([-1.5,1.5])
plt.xlabel('Zeit (s)')
plt.ylabel('Amplitude')
plt.tight_layout()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 10[0m
[1;32m      8[0m PM [38;5;241m=[39m A [38;5;241m*[39m np[38;5;241m.[39msin([38;5;241m2[39m[38;5;241m*[39mnp[38;5;241m.[39mpi[38;5;241m*[39mff[38;5;241m*[39mt [38;5;241m+[39m M_p[38;5;241m*[39my_nutz_norm)
[1;32m      9[0m plt[38;5;241m.[39msubplot([38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m1[39m)
[0;32m---> 10[0m plt[38;5;241m.[39mplot(t, [43my[49m, [38;5;124m'[39m[38;5;124mk[39m[38;5;124m'[39m, ls[38;5;241m=[39m[38;5;124m'[39m[38;5;124m:[39m[38;5;124m'[39m, label [38;5;241m=[39m [38;5;124m'[39m[38;5;124mTr√§ger[39m[38;5;124m'[39m)
[1;32m     11[0m plt[38;5;241m.[39mplot(t,PM, [38;5;124m'[39m[38;5;124mtab:red[39m[38;5;124m'[39m, lw[38;5;241m=[39m[38;5;241m2[39m, alpha [38;5;241m=[39m [38;5;241m0.65[39m, label [38;5;241m=[39m [38;5;124m'[39m[38;5;124mAM[39m[38;5;124m'[39m)
[1;32m     12[0m plt[38;5;241m.[39mplot(t, y_nutz_norm, [38;5;124m'[39m[38;5;124mtab:blue[39m[38;5;124m'[39m, label [38;5;241m=[39m [38;5;124m'[39m[38;5;124mNachricht[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'y' is not defined
NameError: name 'y' is not defined

