Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Ben√∂tigte Libraries:
import numpy as np
import pandas as pd
from scipy import signal 
import scipy.integrate as spi
import matplotlib.pyplot as plt
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls
import seaborn as sns
import time
import warnings
warnings.filterwarnings('ignore')
MatplotLib Settings:
plt.style.use('default') # Matplotlib Style w√§hlen
plt.xkcd()
plt.rcParams['font.size'] = 10; # Schriftgr√∂√üe


def heaviside_step_function(t):
    if t < 0:
        res = 0
    else:
        res = 1
    return res


T = 1
t = np.linspace(-2*T, 2*T, 1000, endpoint = True)
y_step = []
for i in t:
    y_step.append(heaviside_step_function(i))
    
# Plotting
fig, ax = plt.subplots(figsize=(3,2))
plt.plot(t,y_step, color = 'tab:blue')
ax.set_yticks([0,1])
ax.set_xticks([0])
plt.title('Sprungsanregung bei t = 0s')
plt.xlabel('Zeit t')
plt.ylabel(r'$u_e$')
plt.show()
------------------

[0;36m  Input [0;32mIn [1][0;36m[0m
[0;31m    MatplotLib Settings:[0m
[0m               ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax

SyntaxError: invalid syntax (300277215.py, line 15)

