Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from scipy.optimize import fsolve

def nlSystem(aw):
    V_in1 = 2
    V_out1 = 0
    V_in2 = 7
    V_out2 = 10
    Vref = 3.3

    R_1 = aw[0]
    R_2 = 400
    R_3 = 1400
    R_4 = aw[1]

F = np.zeros(2)
F[0] = V_in1 * (R_4 / (R_2 + R_4)) * ((R_3 + R_1) / R_1) - Vref * (R_3 / R_1) - V_out1
F[1] = V_in2 * (R_4 / (R_2 + R_4)) * ((R_3 + R_1) / R_1) - Vref * (R_3 / R_1) - V_out2

return F

# Anfangswerte fÃ¼r [R_1, R_4] (AbschÃ¤tzen)
Anfangswerte = [1, 1]

# Aufrufen der Funktion
loesung = fsolve(nlSystem, Anfangswerte)

# Ausgabe der WiderstÃ¤nde
print(f'R_1 = {loesung[0]}')
print(f'R_4 = {loesung[1]}')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 17[0m
[1;32m     14[0m     R_4 [38;5;241m=[39m aw[[38;5;241m1[39m]
[1;32m     16[0m F [38;5;241m=[39m np[38;5;241m.[39mzeros([38;5;241m2[39m)
[0;32m---> 17[0m F[[38;5;241m0[39m] [38;5;241m=[39m [43mV_in1[49m [38;5;241m*[39m (R_4 [38;5;241m/[39m (R_2 [38;5;241m+[39m R_4)) [38;5;241m*[39m ((R_3 [38;5;241m+[39m R_1) [38;5;241m/[39m R_1) [38;5;241m-[39m Vref [38;5;241m*[39m (R_3 [38;5;241m/[39m R_1) [38;5;241m-[39m V_out1
[1;32m     18[0m F[[38;5;241m1[39m] [38;5;241m=[39m V_in2 [38;5;241m*[39m (R_4 [38;5;241m/[39m (R_2 [38;5;241m+[39m R_4)) [38;5;241m*[39m ((R_3 [38;5;241m+[39m R_1) [38;5;241m/[39m R_1) [38;5;241m-[39m Vref [38;5;241m*[39m (R_3 [38;5;241m/[39m R_1) [38;5;241m-[39m V_out2
[1;32m     20[0m [38;5;28;01mreturn[39;00m F

[0;31mNameError[0m: name 'V_in1' is not defined
NameError: name 'V_in1' is not defined

